### ISSUE TITLE
i got some errors when i run cake clear_cache

### ISSUE THREAD

**Issue by simkimsia** [ceeram/clear_cache#1]
hi, previously i had no problems running cake clear_cache.

please tell me what went wrong.

thank you.
http://bin.cakephp.org/view/257473146

**Comment by ceeram** [comment]
is cache enabled in core.php?
what cache engines do you use?

**Comment by simkimsia** [comment]
Hi Ceeram, my apologies. 

i forgot to comment out the disable Cache line i have in my own  development machine.

Really sorry for raising this.
