### ISSUE TITLE
unable to use ClearCache sometimes to regenerate the cache files. Need to change debug mode in core.php

### ISSUE THREAD

**Issue by simkimsia** [ceeram/clear_cache#15]
Sometimes my cakeapp does not work and what I do is I change the debug mode from 0 to 2 and then refresh and then back from 2 to 0.

http://stackoverflow.com/a/17397109/80353

According to David Yell, what I did was basically to regenerate the cache files.

I have taken his advice and change the mask value. http://stackoverflow.com/questions/17145332/table-for-model-not-found-in-datasource-default/17397109?noredirect=1#comment28569116_17397109

Today I manage to trigger an error regarding the cache files. His suggestion did not work in conjunction with your clear_cache.

Was wondering if you know something about this.

**Comment by ceeram** [comment]
ClearCache is about removing caches from console, app or debugkit panel. Regenerating cache files is CakePHP's job. I don't understand either why the issue occurs, but it surely isnt clear_cache issue, as the SO poster encountered the issue without using clear_cache

**Comment by simkimsia** [comment]
Are you aware of any way to regenerate the cache files?

**Comment by ceeram** [comment]
Cakephp would create them if not present when using file cacheengine
Op 14 okt. 2013 10:49 schreef "simkimsia" notifications@github.com:

**Comment by simkimsia** [comment]
I see. Is there a way to force a regeneration via the Console?

I googled and I can only find information for clearing but not regeneration.

http://book.cakephp.org/2.0/en/core-libraries/helpers/cache.html#clearing-the-cache

**Comment by ceeram** [comment]
You dont need to manually regenerate.
Op 15 okt. 2013 08:05 schreef "simkimsia" notifications@github.com:

**Comment by simkimsia** [comment]
Well, weird errors happen frequently enough whenever I update the production environment either using FTP or jenkins.

These weird errors can only be resolved by me manually changing the debug mode from 0 to 2 and then refresh once and then back again.

If David Yell is right, it involves me having to regenerate the cache files. 

I understand this issue has nothing to do with ClearCache plugin now. Since this is one of the best maintained plugin associated with cache and cakephp, I was wondering if you have any suggestions for me to automate the process of regenerating cache files properly after every time the code base is updated on my production environment.

The situation has occurred in two separate apps hosted in two separate servers. One is for a client system I have developed and hosted in the client internal server. The other is hosted on rackspace. Both are using cakephp2.4.

Sad to say the error is not easily replicated as it happens like about 20%-40% of the time when I update the code base.

**Comment by ceeram** [comment]
File a bugreport at cakephp
Op 15 okt. 2013 09:57 schreef "simkimsia" notifications@github.com:
