### ISSUE TITLE
Problem with import

### ISSUE THREAD

**Issue by markalanevans** [ceeram/clear_cache#2]
I had to use :
    App::import('Lib', 'ClearCache');
Instead of :
    App::import('Libs', 'ClearCache.ClearCache');

-singular "Lib"

-and simply  "ClearCache"

And have my files organized like this:
in /app/libs/clear_cache.php
and /app/vendors/shells/clear_cache.php

im using 1.3 do you have it setup some other way?

**Comment by ceeram** [comment]
You need the plugin prefix only when you use this lib from the plugin. See the cake cookbook on how to use plugin prefixes

**Comment by markalanevans** [comment]
That would be it.. I didn't know it was a plugin... I did it your way as a plugin and everything is gold.   Any chance you wrote a post-merge git script????
