### ISSUE TITLE
Bug when not using Routing Prefixes

### ISSUE THREAD

**Issue by challgren** [ceeram/clear_cache#20]
My CakePHP 2.5.5 site doesn't use routing prefixes. When using the debug_kit panel the following error is displayed 

```
Clear Cache

Warning (2): Invalid argument supplied for foreach() [APP\Plugin\ClearCache\View\Elements\clear_cache_panel.ctp, line 21]Files: All Cached Files | minify | models | persistent | views
Engines:
Warning (2): Invalid argument supplied for foreach() [APP\Plugin\ClearCache\View\Elements\clear_cache_panel.ctp, line 50]All Cache Engines | _cake_core_ | _cake_model_ | default
```

I was able to fix it by adding the following to my Core.php `Configure::write('Routing.prefixes', array('admin'));` Maybe catching the error and displaying a friendly message.

**Comment by tersmitten** [comment]
We see the same error
