### ISSUE TITLE
Fatal Error: Class 'ClearCache' not found

### ISSUE THREAD

**Issue by geodinca** [ceeram/clear_cache#4]
Hi, I tried your extension in a project - Cake 1.3.6
I downloaded v. 0.2 

I tried to put files in cake root /lin\bs and vendors directories or in app/libs and /app/vendors

In both situation I receice the following:
user@local:~/www/aps$ cake/console/cake clear_cache

Fatal error: Class 'ClearCache' not found in /home/user/www/aps/app/vendors/shells/clear_cache.php on line 89

**Comment by ceeram** [comment]
this is to be used as plugin, if you take out the files you need to drop Clearcache prefix when loading the class

**Comment by ceeram** [comment]
Another is not changing the code and do:

put all files in app/plugins/clear_cache or /plugins/clear_cache
entering the command: "cake"
should give you all available shells including the clear_cache

**Comment by ceeram** [comment]
more info: https://github.com/ceeram/clear_cache/issues/2

**Comment by geodinca** [comment]
Thank you for promt response, I manage meenwile to reinvent the https://github.com/ceeram/clear_cache/issues/2 solution :).

Putting files in Plugin directory make sence now!
